---
services:
  dump1090-exporter:
    image: ghcr.io/mmkay/dump1090-exporter:main
    container_name: dump1090-exporter
    environment:
      - RESOURCE_PATH=http://localhost:8080/data/
    ports:
      - 9105:9105
    restart: unless-stopped