{
 "title": "ais-exporter",
 "description": "This dashboard displays ais metrics that get exposed to Prometheus by the ais-exporter.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ships Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ais_recent_ships_observed{job=\"ais\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "ships w/ Position",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ais_recent_ships_with_position{job=\"ais\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ais_recent_ships_max_range{job=\"ais\"}"
    }
   ]
  },
  {
   "title": "Messages/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(ais_messages_total{job=\"ais\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ais_stats_local_peak_signal_strength_dbFS{job=\"ais\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Mean",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ais_stats_local_signal_strength_dbFS{job=\"ais\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "ships",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ais_recent_ships_observed{job=\"ais\", time_period=\"latest\"}",
     "legendFormat": "total"
    },
    {
     "expr": "ais_recent_ships_with_position{job=\"ais\", time_period=\"latest\"}",
     "legendFormat": "W/ position"
    },
    {
     "expr": "ais_recent_ships_observed{job=\"ais\", time_period=\"latest\"} - ais_recent_ships_with_position{job=\"ais\", time_period=\"latest\"}",
     "legendFormat": "Wo/ position"
    },
    {
     "expr": "ais_recent_ships_with_multilateration{job=\"ais\", time_period=\"latest\"}",
     "legendFormat": "mlat"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "content": "#### ships\nThis graph displays the counts of ships (e.g unique ICAO) being reported. ships are grouped into total ships being reported, ships reported with a position, ships reported without a position and ships reported that have multi-lateration reports."
  },
  {
   "title": "Maximum Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "ais_recent_ships_max_range{job=\"ais\", time_period=\"latest\"}",
     "legendFormat": "{{ time_period }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "content": "##### Maximum Range\nThis graph displays the maximum range of the currently observed ships reporting a position."
  },
  {
   "title": "messages / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ais_messages_total{job=\"ais\", time_period=\"latest\"}[1m])",
     "legendFormat": "latest"
    },
    {
     "expr": "ais_stats_messages_total{job=\"ais\", time_period=\"last1min\"} / 60",
     "legendFormat": "last1min"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "content": "##### Messages\nThis graph displays the messages received per second."
  },
  {
   "title": "Signal Strength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "dbFS" }
   ],
   "targets": [
    {
     "expr": "ais_stats_local_signal_strength_dbFS{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "ais_stats_local_peak_signal_strength_dbFS{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "ais_stats_local_noise_level_dbFS{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "noise"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "content": "##### Signal Strength\nThis graph displays the signal levels reported for noise, mean and peak signal levels. The values are reported in [dbFS](https://en.wikipedia.org/wiki/DBFS)."
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ais_stats_cpu_demod_milliseconds{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "demod"
    },
    {
     "expr": "ais_stats_cpu_reader_milliseconds{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "usb"
    },
    {
     "expr": "ais_stats_cpu_background_milliseconds{job=\"ais\", time_period=\"last1min\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "content": "##### CPU Utilisation\nThis graph displays how much CPU time is used by the ais tool. demod reports the time spent demodulating and decoding data from the USB SDR dongle. usb reports time spent reading sample data from the USB SDR dongle. other reports time spent doing network I/O, processing network messages, and periodic tasks.\n"
  }
 ]
}