{
 "title": "Ships",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Ships",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ais_lat", "legendFormat": "__auto" },
    { "expr": "ais_lon", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spotted sships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (mmsi) (ais_lat))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ships with name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (ais_lat))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ships by country",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 8, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "topk(50, count by (country) (ais_lat))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}