version: '3'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:

  ais-exporter:
    container_name: ais-exporter
    build: ${PWD}/..
    ports:
      - "9205:9205"
    restart: always
    stop_signal: SIGINT
    command: [
      "--resource-path=http://192.168.1.201:8080",
      "--latitude=-34.9285",
      "--longitude=138.6007"]

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    depends_on:
      - ais-exporter
    volumes:
      - ${PWD}/prometheus/:/etc/prometheus/
      - ${PWD}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/grafana:/var/lib/grafana
      - ${PWD}/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
